# ==============================================================================
# Mechanics to be identified
# ==============================================================================
GetMechanics <- function() {
  values <- c(
    "Backtracking",
    "Boss",
    "Bullet Time",
    "Car Chase",
    "Championship",
    "Character Customization",
    "Checkpoint",
    "Climbing",
    "Collectibles",
    "Combo",
    "Companion",
    "Costume",
    "Cover System",
    "Crafting",
    "Critical Hit",
    "Customization",
    "Destructible Environment",
    "Dialog Tree",
    "Dodge / Evage",
    "Drift",
    "Driving",
    "Exploration",
    "Explosion",
    "Fast Travel",
    "Fatality",
    "Fire",
    "Fog of War",
    "Free Roam",
    "Grinding",
    "HP",
    "Jump",
    "Levelling",
    "Looting",
    "Luck",
    "MP",
    "Magic",
    "Meele",
    "Micromanagement",
    "Minimap",
    "Multiple Endings",
    "New Game Plus",
    "Nitro",
    "Physics",
    "Portal",
    "Potion",
    "Quest",
    "Quick Save",
    "Quick Time Event",
    "Quick Travel",
    "Radar",
    "Respawn",
    "Round",
    "Sandbox",
    "Side Mission /  Side Quest",
    "Skill Tree",
    "Squad",
    "Stage",
    "Telekinesis",
    "Theft",
    "Time Travel",
    "Timer",
    "Tournament",
    "Trap",
    "Tuning",
    "Turn-Based",
    "Vehicle Customization",
    "Weapon Customization",
    "World Map"
  )

  return(values)
}
